---
name: Full Release

on:
  workflow_dispatch:

jobs:
  bump-npm:
    name: bump npm version
    uses: ./.github/workflows/bump-npm-version.yaml
  gh-release:
    name: create gh release
    needs: bump-npm
    uses: ./.github/workflows/create-github-release.yaml
  ghcr-push:
    name: push to GHCR
    needs: gh-release
    uses: ./.github/workflows/build-and-push-docker-image.yaml
